name: Build Kernel
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Build Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential ccache curl flex git gnupg gperf imagemagick liblz4-tool libncurses5-dev libssl-dev libxml2 libxml2-utils lzop rsync schedtool squashfs-tools xsltproc zip zlib1g-dev gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi

      - name: Download Proton Clang
        run: git clone https://github.com/kdrag0n/proton-clang.git --depth=1 ~/proton-clang

      - name: Download LineageOS Kernel
        run: git clone https://github.com/LineageOS/android_kernel_oneplus_sm6375.git -b lineage-23.2 --depth=1 ~/kernel

      - name: Apply Monitor Mode Patch
        run: |
          cd ~/kernel/drivers/staging/qcacld-3.0
          find . -type f \( -name "Kbuild" -o -name "Makefile" -o -name "*.mk" -o -name "*defconfig" \) -exec sed -i 's/CONFIG_FEATURE_MONITOR_MODE_SUPPORT := n/CONFIG_FEATURE_MONITOR_MODE_SUPPORT := y/g' {} +

      - name: Fix sy6529 condition
        run: |
          cd ~/kernel
          python - <<'PY'
          from pathlib import Path
          p = Path("drivers/power/oplus/v1/voocphy/oplus_sy6529.c")
          text = p.read_text()
          old = "if (*data == sy6529_CHARGE_MODE_2_1 | *data == sy6529_CHARGE_MODE_1_1)"
          new = "if ((*data == sy6529_CHARGE_MODE_2_1) || (*data == sy6529_CHARGE_MODE_1_1))"
          if old not in text:
              raise SystemExit("pattern not found in sy6529.c")
          p.write_text(text.replace(old, new))
          PY

      - name: Fix nu1619 condition
        run: |
          cd ~/kernel
          python - <<'PY'
          from pathlib import Path

          p = Path("drivers/power/oplus/v1/wireless_ic/oplus_nu1619.c")
          text = p.read_text()

          old = "if (nu1619_get_CEP_flag(chip) == 0 && adjust_current_delay == 0)"
          new = "if ((nu1619_get_CEP_flag(chip) == 0) && (adjust_current_delay == 0))"

          if old not in text:
              raise SystemExit("pattern not found in oplus_nu1619.c")

          p.write_text(text.replace(old, new, 1))
          PY
    
      - name: Compile the Kernel
        run: |
          cd ~/kernel
          export ARCH=arm64
          export SUBARCH=arm64
          export PATH="$HOME/proton-clang/bin:$PATH"
          export CC=clang
          export CROSS_COMPILE=aarch64-linux-gnu-
          export CROSS_COMPILE_ARM32=arm-linux-gnueabi-
          export AR=llvm-ar
          export NM=llvm-nm
          export OBJCOPY=llvm-objcopy
          export OBJDUMP=llvm-objdump
          export STRIP=llvm-strip
          
          make O=out vendor/holi-qgki_defconfig
          make O=out -j$(nproc) KCFLAGS="-Wno-error"

      - name: Upload Finished Kernel
        uses: actions/upload-artifact@v4
        with:
          name: compiled-kernel
          path: ~/kernel/out/arch/arm64/boot/Image
